/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AddImagesToPostBody,
  AddImagesToPostParams,
  AddPoastDiscriptionParams,
  AddPostWithFileBody,
  AddRatingParams,
  AddVoteParams,
  ApiErrorResponse,
  ApiSuccessResponse,
  DashboardCountsResponse,
  DeleteImagesFromPostParams,
  DescriptionDeleteParams,
  GetPostDiscriptionParams,
  PostDeleteParams,
  UpdatePostBody,
  UpdatePostDiscriptionParams,
  UpdatePostParams,
} from '../../models'

import { coreBackendClient } from '../../../utils/http/clients/coreBackend.client'

export type addImagesToPostResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type addImagesToPostResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type addImagesToPostResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type addImagesToPostResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type addImagesToPostResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type addImagesToPostResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type addImagesToPostResponseSuccess = addImagesToPostResponse200 & {
  headers: Headers
}
export type addImagesToPostResponseError = (
  | addImagesToPostResponse400
  | addImagesToPostResponse401
  | addImagesToPostResponse403
  | addImagesToPostResponse422
  | addImagesToPostResponse500
) & {
  headers: Headers
}

export type addImagesToPostResponse = addImagesToPostResponseSuccess | addImagesToPostResponseError

export const getAddImagesToPostUrl = (params: AddImagesToPostParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/addImagesToPost?${stringifiedParams}`
    : `/post/addImagesToPost`
}

/**
 * Adds one or more images to an owned post while enforcing extension, size, and max image-count rules.
 * @summary Add images to post
 */
export const addImagesToPost = async (
  params: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody,
  options?: RequestInit
): Promise<addImagesToPostResponse> => {
  return coreBackendClient<addImagesToPostResponse>(getAddImagesToPostUrl(params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addImagesToPostBody),
  })
}

export const getAddImagesToPostQueryKey = (
  params?: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody
) => {
  return [
    'POST',
    `/post/addImagesToPost`,
    ...(params ? [params] : []),
    addImagesToPostBody,
  ] as const
}

export const getAddImagesToPostQueryOptions = <
  TData = Awaited<ReturnType<typeof addImagesToPost>>,
  TError = ApiErrorResponse,
>(
  params: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addImagesToPost>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAddImagesToPostQueryKey(params, addImagesToPostBody)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addImagesToPost>>> = ({ signal }) =>
    addImagesToPost(params, addImagesToPostBody, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addImagesToPost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddImagesToPostQueryResult = NonNullable<Awaited<ReturnType<typeof addImagesToPost>>>
export type AddImagesToPostQueryError = ApiErrorResponse

export function useAddImagesToPost<
  TData = Awaited<ReturnType<typeof addImagesToPost>>,
  TError = ApiErrorResponse,
>(
  params: AddImagesToPostParams,
  addImagesToPostBody: undefined | AddImagesToPostBody,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof addImagesToPost>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof addImagesToPost>>,
        TError,
        Awaited<ReturnType<typeof addImagesToPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddImagesToPost<
  TData = Awaited<ReturnType<typeof addImagesToPost>>,
  TError = ApiErrorResponse,
>(
  params: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addImagesToPost>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof addImagesToPost>>,
        TError,
        Awaited<ReturnType<typeof addImagesToPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddImagesToPost<
  TData = Awaited<ReturnType<typeof addImagesToPost>>,
  TError = ApiErrorResponse,
>(
  params: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addImagesToPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Add images to post
 */

export function useAddImagesToPost<
  TData = Awaited<ReturnType<typeof addImagesToPost>>,
  TError = ApiErrorResponse,
>(
  params: AddImagesToPostParams,
  addImagesToPostBody?: AddImagesToPostBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addImagesToPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddImagesToPostQueryOptions(params, addImagesToPostBody, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type addPoastDiscriptionResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type addPoastDiscriptionResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type addPoastDiscriptionResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type addPoastDiscriptionResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type addPoastDiscriptionResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type addPoastDiscriptionResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type addPoastDiscriptionResponseSuccess = addPoastDiscriptionResponse200 & {
  headers: Headers
}
export type addPoastDiscriptionResponseError = (
  | addPoastDiscriptionResponse400
  | addPoastDiscriptionResponse401
  | addPoastDiscriptionResponse403
  | addPoastDiscriptionResponse422
  | addPoastDiscriptionResponse500
) & {
  headers: Headers
}

export type addPoastDiscriptionResponse =
  | addPoastDiscriptionResponseSuccess
  | addPoastDiscriptionResponseError

export const getAddPoastDiscriptionUrl = (params: AddPoastDiscriptionParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/addPoastDiscription?${stringifiedParams}`
    : `/post/addPoastDiscription`
}

/**
 * Adds a user-authored description/comment to a post after content moderation. Endpoint spelling preserves the existing API contract.
 * @summary Add post description
 */
export const addPoastDiscription = async (
  params: AddPoastDiscriptionParams,
  options?: RequestInit
): Promise<addPoastDiscriptionResponse> => {
  return coreBackendClient<addPoastDiscriptionResponse>(getAddPoastDiscriptionUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getAddPoastDiscriptionQueryKey = (params?: AddPoastDiscriptionParams) => {
  return ['POST', `/post/addPoastDiscription`, ...(params ? [params] : [])] as const
}

export const getAddPoastDiscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof addPoastDiscription>>,
  TError = ApiErrorResponse,
>(
  params: AddPoastDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPoastDiscription>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAddPoastDiscriptionQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addPoastDiscription>>> = ({ signal }) =>
    addPoastDiscription(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addPoastDiscription>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddPoastDiscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof addPoastDiscription>>
>
export type AddPoastDiscriptionQueryError = ApiErrorResponse

export function useAddPoastDiscription<
  TData = Awaited<ReturnType<typeof addPoastDiscription>>,
  TError = ApiErrorResponse,
>(
  params: AddPoastDiscriptionParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof addPoastDiscription>>, TError, TData>
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof addPoastDiscription>>,
        TError,
        Awaited<ReturnType<typeof addPoastDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddPoastDiscription<
  TData = Awaited<ReturnType<typeof addPoastDiscription>>,
  TError = ApiErrorResponse,
>(
  params: AddPoastDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof addPoastDiscription>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof addPoastDiscription>>,
        TError,
        Awaited<ReturnType<typeof addPoastDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddPoastDiscription<
  TData = Awaited<ReturnType<typeof addPoastDiscription>>,
  TError = ApiErrorResponse,
>(
  params: AddPoastDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPoastDiscription>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Add post description
 */

export function useAddPoastDiscription<
  TData = Awaited<ReturnType<typeof addPoastDiscription>>,
  TError = ApiErrorResponse,
>(
  params: AddPoastDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPoastDiscription>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddPoastDiscriptionQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type addPostWithFileResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type addPostWithFileResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type addPostWithFileResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type addPostWithFileResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type addPostWithFileResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type addPostWithFileResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type addPostWithFileResponseSuccess = addPostWithFileResponse200 & {
  headers: Headers
}
export type addPostWithFileResponseError = (
  | addPostWithFileResponse400
  | addPostWithFileResponse401
  | addPostWithFileResponse403
  | addPostWithFileResponse422
  | addPostWithFileResponse500
) & {
  headers: Headers
}

export type addPostWithFileResponse = addPostWithFileResponseSuccess | addPostWithFileResponseError

export const getAddPostWithFileUrl = () => {
  return `/post/addPostWithFile`
}

/**
 * Creates an inscription post from multipart metadata and one or more images. The server validates extension, image count, size, metadata, geolocation, perceptual hash data, and content moderation.
 * @summary Create post with images
 */
export const addPostWithFile = async (
  addPostWithFileBody?: AddPostWithFileBody,
  options?: RequestInit
): Promise<addPostWithFileResponse> => {
  return coreBackendClient<addPostWithFileResponse>(getAddPostWithFileUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addPostWithFileBody),
  })
}

export const getAddPostWithFileQueryKey = (addPostWithFileBody?: AddPostWithFileBody) => {
  return ['POST', `/post/addPostWithFile`, addPostWithFileBody] as const
}

export const getAddPostWithFileQueryOptions = <
  TData = Awaited<ReturnType<typeof addPostWithFile>>,
  TError = ApiErrorResponse,
>(
  addPostWithFileBody?: AddPostWithFileBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPostWithFile>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAddPostWithFileQueryKey(addPostWithFileBody)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addPostWithFile>>> = ({ signal }) =>
    addPostWithFile(addPostWithFileBody, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addPostWithFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddPostWithFileQueryResult = NonNullable<Awaited<ReturnType<typeof addPostWithFile>>>
export type AddPostWithFileQueryError = ApiErrorResponse

export function useAddPostWithFile<
  TData = Awaited<ReturnType<typeof addPostWithFile>>,
  TError = ApiErrorResponse,
>(
  addPostWithFileBody: undefined | AddPostWithFileBody,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPostWithFile>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof addPostWithFile>>,
        TError,
        Awaited<ReturnType<typeof addPostWithFile>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddPostWithFile<
  TData = Awaited<ReturnType<typeof addPostWithFile>>,
  TError = ApiErrorResponse,
>(
  addPostWithFileBody?: AddPostWithFileBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPostWithFile>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof addPostWithFile>>,
        TError,
        Awaited<ReturnType<typeof addPostWithFile>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddPostWithFile<
  TData = Awaited<ReturnType<typeof addPostWithFile>>,
  TError = ApiErrorResponse,
>(
  addPostWithFileBody?: AddPostWithFileBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPostWithFile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create post with images
 */

export function useAddPostWithFile<
  TData = Awaited<ReturnType<typeof addPostWithFile>>,
  TError = ApiErrorResponse,
>(
  addPostWithFileBody?: AddPostWithFileBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addPostWithFile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddPostWithFileQueryOptions(addPostWithFileBody, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type addRatingResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type addRatingResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type addRatingResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type addRatingResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type addRatingResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type addRatingResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type addRatingResponseSuccess = addRatingResponse200 & {
  headers: Headers
}
export type addRatingResponseError = (
  | addRatingResponse400
  | addRatingResponse401
  | addRatingResponse403
  | addRatingResponse422
  | addRatingResponse500
) & {
  headers: Headers
}

export type addRatingResponse = addRatingResponseSuccess | addRatingResponseError

export const getAddRatingUrl = (params: AddRatingParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/post/addRating?${stringifiedParams}` : `/post/addRating`
}

/**
 * Adds or updates the authenticated user's numeric rating for a post.
 * @summary Rate post
 */
export const addRating = async (
  params: AddRatingParams,
  options?: RequestInit
): Promise<addRatingResponse> => {
  return coreBackendClient<addRatingResponse>(getAddRatingUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getAddRatingQueryKey = (params?: AddRatingParams) => {
  return ['POST', `/post/addRating`, ...(params ? [params] : [])] as const
}

export const getAddRatingQueryOptions = <
  TData = Awaited<ReturnType<typeof addRating>>,
  TError = ApiErrorResponse,
>(
  params: AddRatingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addRating>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAddRatingQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addRating>>> = ({ signal }) =>
    addRating(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addRating>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddRatingQueryResult = NonNullable<Awaited<ReturnType<typeof addRating>>>
export type AddRatingQueryError = ApiErrorResponse

export function useAddRating<
  TData = Awaited<ReturnType<typeof addRating>>,
  TError = ApiErrorResponse,
>(
  params: AddRatingParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof addRating>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof addRating>>,
        TError,
        Awaited<ReturnType<typeof addRating>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddRating<
  TData = Awaited<ReturnType<typeof addRating>>,
  TError = ApiErrorResponse,
>(
  params: AddRatingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addRating>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof addRating>>,
        TError,
        Awaited<ReturnType<typeof addRating>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddRating<
  TData = Awaited<ReturnType<typeof addRating>>,
  TError = ApiErrorResponse,
>(
  params: AddRatingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addRating>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Rate post
 */

export function useAddRating<
  TData = Awaited<ReturnType<typeof addRating>>,
  TError = ApiErrorResponse,
>(
  params: AddRatingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addRating>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddRatingQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type addVoteResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type addVoteResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type addVoteResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type addVoteResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type addVoteResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type addVoteResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type addVoteResponseSuccess = addVoteResponse200 & {
  headers: Headers
}
export type addVoteResponseError = (
  | addVoteResponse400
  | addVoteResponse401
  | addVoteResponse403
  | addVoteResponse422
  | addVoteResponse500
) & {
  headers: Headers
}

export type addVoteResponse = addVoteResponseSuccess | addVoteResponseError

export const getAddVoteUrl = (params: AddVoteParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/post/addVote?${stringifiedParams}` : `/post/addVote`
}

/**
 * Adds an upvote when the authenticated user has not voted, or removes the existing vote.
 * @summary Toggle description vote
 */
export const addVote = async (
  params: AddVoteParams,
  options?: RequestInit
): Promise<addVoteResponse> => {
  return coreBackendClient<addVoteResponse>(getAddVoteUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getAddVoteQueryKey = (params?: AddVoteParams) => {
  return ['POST', `/post/addVote`, ...(params ? [params] : [])] as const
}

export const getAddVoteQueryOptions = <
  TData = Awaited<ReturnType<typeof addVote>>,
  TError = ApiErrorResponse,
>(
  params: AddVoteParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addVote>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAddVoteQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addVote>>> = ({ signal }) =>
    addVote(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addVote>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddVoteQueryResult = NonNullable<Awaited<ReturnType<typeof addVote>>>
export type AddVoteQueryError = ApiErrorResponse

export function useAddVote<TData = Awaited<ReturnType<typeof addVote>>, TError = ApiErrorResponse>(
  params: AddVoteParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof addVote>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof addVote>>,
        TError,
        Awaited<ReturnType<typeof addVote>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddVote<TData = Awaited<ReturnType<typeof addVote>>, TError = ApiErrorResponse>(
  params: AddVoteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addVote>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof addVote>>,
        TError,
        Awaited<ReturnType<typeof addVote>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddVote<TData = Awaited<ReturnType<typeof addVote>>, TError = ApiErrorResponse>(
  params: AddVoteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addVote>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Toggle description vote
 */

export function useAddVote<TData = Awaited<ReturnType<typeof addVote>>, TError = ApiErrorResponse>(
  params: AddVoteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addVote>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddVoteQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type deleteImagesFromPostResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type deleteImagesFromPostResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type deleteImagesFromPostResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type deleteImagesFromPostResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type deleteImagesFromPostResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type deleteImagesFromPostResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type deleteImagesFromPostResponseSuccess = deleteImagesFromPostResponse200 & {
  headers: Headers
}
export type deleteImagesFromPostResponseError = (
  | deleteImagesFromPostResponse400
  | deleteImagesFromPostResponse401
  | deleteImagesFromPostResponse403
  | deleteImagesFromPostResponse422
  | deleteImagesFromPostResponse500
) & {
  headers: Headers
}

export type deleteImagesFromPostResponse =
  | deleteImagesFromPostResponseSuccess
  | deleteImagesFromPostResponseError

export const getDeleteImagesFromPostUrl = (params: DeleteImagesFromPostParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/deleteImagesFromPost?${stringifiedParams}`
    : `/post/deleteImagesFromPost`
}

/**
 * Deletes selected images from an owned post while ensuring the post still has at least one image.
 * @summary Delete post images
 */
export const deleteImagesFromPost = async (
  params: DeleteImagesFromPostParams,
  options?: RequestInit
): Promise<deleteImagesFromPostResponse> => {
  return coreBackendClient<deleteImagesFromPostResponse>(getDeleteImagesFromPostUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getDeleteImagesFromPostQueryKey = (params?: DeleteImagesFromPostParams) => {
  return ['POST', `/post/deleteImagesFromPost`, ...(params ? [params] : [])] as const
}

export const getDeleteImagesFromPostQueryOptions = <
  TData = Awaited<ReturnType<typeof deleteImagesFromPost>>,
  TError = ApiErrorResponse,
>(
  params: DeleteImagesFromPostParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deleteImagesFromPost>>, TError, TData>
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDeleteImagesFromPostQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteImagesFromPost>>> = ({ signal }) =>
    deleteImagesFromPost(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof deleteImagesFromPost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteImagesFromPostQueryResult = NonNullable<
  Awaited<ReturnType<typeof deleteImagesFromPost>>
>
export type DeleteImagesFromPostQueryError = ApiErrorResponse

export function useDeleteImagesFromPost<
  TData = Awaited<ReturnType<typeof deleteImagesFromPost>>,
  TError = ApiErrorResponse,
>(
  params: DeleteImagesFromPostParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deleteImagesFromPost>>, TError, TData>
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof deleteImagesFromPost>>,
        TError,
        Awaited<ReturnType<typeof deleteImagesFromPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteImagesFromPost<
  TData = Awaited<ReturnType<typeof deleteImagesFromPost>>,
  TError = ApiErrorResponse,
>(
  params: DeleteImagesFromPostParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deleteImagesFromPost>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof deleteImagesFromPost>>,
        TError,
        Awaited<ReturnType<typeof deleteImagesFromPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteImagesFromPost<
  TData = Awaited<ReturnType<typeof deleteImagesFromPost>>,
  TError = ApiErrorResponse,
>(
  params: DeleteImagesFromPostParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deleteImagesFromPost>>, TError, TData>
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete post images
 */

export function useDeleteImagesFromPost<
  TData = Awaited<ReturnType<typeof deleteImagesFromPost>>,
  TError = ApiErrorResponse,
>(
  params: DeleteImagesFromPostParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deleteImagesFromPost>>, TError, TData>
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDeleteImagesFromPostQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type descriptionDeleteResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type descriptionDeleteResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type descriptionDeleteResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type descriptionDeleteResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type descriptionDeleteResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type descriptionDeleteResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type descriptionDeleteResponseSuccess = descriptionDeleteResponse200 & {
  headers: Headers
}
export type descriptionDeleteResponseError = (
  | descriptionDeleteResponse400
  | descriptionDeleteResponse401
  | descriptionDeleteResponse403
  | descriptionDeleteResponse422
  | descriptionDeleteResponse500
) & {
  headers: Headers
}

export type descriptionDeleteResponse =
  | descriptionDeleteResponseSuccess
  | descriptionDeleteResponseError

export const getDescriptionDeleteUrl = (params: DescriptionDeleteParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/discriptionDelete?${stringifiedParams}`
    : `/post/discriptionDelete`
}

/**
 * Deletes a description/comment owned by the authenticated user. Endpoint spelling preserves the existing API contract.
 * @summary Delete my description
 */
export const descriptionDelete = async (
  params: DescriptionDeleteParams,
  options?: RequestInit
): Promise<descriptionDeleteResponse> => {
  return coreBackendClient<descriptionDeleteResponse>(getDescriptionDeleteUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getDescriptionDeleteQueryKey = (params?: DescriptionDeleteParams) => {
  return ['POST', `/post/discriptionDelete`, ...(params ? [params] : [])] as const
}

export const getDescriptionDeleteQueryOptions = <
  TData = Awaited<ReturnType<typeof descriptionDelete>>,
  TError = ApiErrorResponse,
>(
  params: DescriptionDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof descriptionDelete>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDescriptionDeleteQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof descriptionDelete>>> = ({ signal }) =>
    descriptionDelete(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof descriptionDelete>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DescriptionDeleteQueryResult = NonNullable<
  Awaited<ReturnType<typeof descriptionDelete>>
>
export type DescriptionDeleteQueryError = ApiErrorResponse

export function useDescriptionDelete<
  TData = Awaited<ReturnType<typeof descriptionDelete>>,
  TError = ApiErrorResponse,
>(
  params: DescriptionDeleteParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof descriptionDelete>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof descriptionDelete>>,
        TError,
        Awaited<ReturnType<typeof descriptionDelete>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDescriptionDelete<
  TData = Awaited<ReturnType<typeof descriptionDelete>>,
  TError = ApiErrorResponse,
>(
  params: DescriptionDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof descriptionDelete>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof descriptionDelete>>,
        TError,
        Awaited<ReturnType<typeof descriptionDelete>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDescriptionDelete<
  TData = Awaited<ReturnType<typeof descriptionDelete>>,
  TError = ApiErrorResponse,
>(
  params: DescriptionDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof descriptionDelete>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete my description
 */

export function useDescriptionDelete<
  TData = Awaited<ReturnType<typeof descriptionDelete>>,
  TError = ApiErrorResponse,
>(
  params: DescriptionDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof descriptionDelete>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDescriptionDeleteQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getAllPostResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type getAllPostResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getAllPostResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getAllPostResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getAllPostResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getAllPostResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getAllPostResponseSuccess = getAllPostResponse200 & {
  headers: Headers
}
export type getAllPostResponseError = (
  | getAllPostResponse400
  | getAllPostResponse401
  | getAllPostResponse403
  | getAllPostResponse422
  | getAllPostResponse500
) & {
  headers: Headers
}

export type getAllPostResponse = getAllPostResponseSuccess | getAllPostResponseError

export const getGetAllPostUrl = () => {
  return `/post/getAllPost`
}

/**
 * Returns all posts with image identifiers expanded to public image URLs.
 * @summary List all visible posts
 */
export const getAllPost = async (options?: RequestInit): Promise<getAllPostResponse> => {
  return coreBackendClient<getAllPostResponse>(getGetAllPostUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getGetAllPostQueryKey = () => {
  return ['POST', `/post/getAllPost`] as const
}

export const getGetAllPostQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllPost>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPost>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllPostQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPost>>> = ({ signal }) =>
    getAllPost({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllPost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllPostQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPost>>>
export type GetAllPostQueryError = ApiErrorResponse

export function useGetAllPost<
  TData = Awaited<ReturnType<typeof getAllPost>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPost>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllPost>>,
        TError,
        Awaited<ReturnType<typeof getAllPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPost<
  TData = Awaited<ReturnType<typeof getAllPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPost>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllPost>>,
        TError,
        Awaited<ReturnType<typeof getAllPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPost<
  TData = Awaited<ReturnType<typeof getAllPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all visible posts
 */

export function useGetAllPost<
  TData = Awaited<ReturnType<typeof getAllPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllPostQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getAllUserPostResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type getAllUserPostResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getAllUserPostResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getAllUserPostResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getAllUserPostResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getAllUserPostResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getAllUserPostResponseSuccess = getAllUserPostResponse200 & {
  headers: Headers
}
export type getAllUserPostResponseError = (
  | getAllUserPostResponse400
  | getAllUserPostResponse401
  | getAllUserPostResponse403
  | getAllUserPostResponse422
  | getAllUserPostResponse500
) & {
  headers: Headers
}

export type getAllUserPostResponse = getAllUserPostResponseSuccess | getAllUserPostResponseError

export const getGetAllUserPostUrl = () => {
  return `/post/getAllUserPost`
}

/**
 * Returns posts created by the authenticated user with image URLs hydrated.
 * @summary List my posts
 */
export const getAllUserPost = async (options?: RequestInit): Promise<getAllUserPostResponse> => {
  return coreBackendClient<getAllUserPostResponse>(getGetAllUserPostUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getGetAllUserPostQueryKey = () => {
  return ['POST', `/post/getAllUserPost`] as const
}

export const getGetAllUserPostQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUserPost>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUserPost>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllUserPostQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUserPost>>> = ({ signal }) =>
    getAllUserPost({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUserPost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUserPostQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUserPost>>>
export type GetAllUserPostQueryError = ApiErrorResponse

export function useGetAllUserPost<
  TData = Awaited<ReturnType<typeof getAllUserPost>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUserPost>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllUserPost>>,
        TError,
        Awaited<ReturnType<typeof getAllUserPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUserPost<
  TData = Awaited<ReturnType<typeof getAllUserPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUserPost>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllUserPost>>,
        TError,
        Awaited<ReturnType<typeof getAllUserPost>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUserPost<
  TData = Awaited<ReturnType<typeof getAllUserPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUserPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my posts
 */

export function useGetAllUserPost<
  TData = Awaited<ReturnType<typeof getAllUserPost>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUserPost>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllUserPostQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getCommentByUserResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type getCommentByUserResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getCommentByUserResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getCommentByUserResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getCommentByUserResponseSuccess = getCommentByUserResponse200 & {
  headers: Headers
}
export type getCommentByUserResponseError = (
  | getCommentByUserResponse400
  | getCommentByUserResponse422
  | getCommentByUserResponse500
) & {
  headers: Headers
}

export type getCommentByUserResponse =
  | getCommentByUserResponseSuccess
  | getCommentByUserResponseError

export const getGetCommentByUserUrl = () => {
  return `/post/getCommentByUser`
}

/**
 * Returns descriptions/comments authored by the authenticated user with post preview image URLs.
 * @summary List my descriptions
 */
export const getCommentByUser = async (
  options?: RequestInit
): Promise<getCommentByUserResponse> => {
  return coreBackendClient<getCommentByUserResponse>(getGetCommentByUserUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getGetCommentByUserQueryKey = () => {
  return ['POST', `/post/getCommentByUser`] as const
}

export const getGetCommentByUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCommentByUser>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentByUser>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCommentByUserQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentByUser>>> = ({ signal }) =>
    getCommentByUser({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCommentByUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentByUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCommentByUser>>>
export type GetCommentByUserQueryError = ApiErrorResponse

export function useGetCommentByUser<
  TData = Awaited<ReturnType<typeof getCommentByUser>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentByUser>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getCommentByUser>>,
        TError,
        Awaited<ReturnType<typeof getCommentByUser>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentByUser<
  TData = Awaited<ReturnType<typeof getCommentByUser>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentByUser>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getCommentByUser>>,
        TError,
        Awaited<ReturnType<typeof getCommentByUser>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentByUser<
  TData = Awaited<ReturnType<typeof getCommentByUser>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentByUser>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my descriptions
 */

export function useGetCommentByUser<
  TData = Awaited<ReturnType<typeof getCommentByUser>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentByUser>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCommentByUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getPostDiscriptionResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type getPostDiscriptionResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getPostDiscriptionResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getPostDiscriptionResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getPostDiscriptionResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getPostDiscriptionResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getPostDiscriptionResponseSuccess = getPostDiscriptionResponse200 & {
  headers: Headers
}
export type getPostDiscriptionResponseError = (
  | getPostDiscriptionResponse400
  | getPostDiscriptionResponse401
  | getPostDiscriptionResponse403
  | getPostDiscriptionResponse422
  | getPostDiscriptionResponse500
) & {
  headers: Headers
}

export type getPostDiscriptionResponse =
  | getPostDiscriptionResponseSuccess
  | getPostDiscriptionResponseError

export const getGetPostDiscriptionUrl = (params: GetPostDiscriptionParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/getPostDiscription?${stringifiedParams}`
    : `/post/getPostDiscription`
}

/**
 * Returns all user descriptions/comments for a post. Endpoint spelling preserves the existing API contract.
 * @summary List post descriptions
 */
export const getPostDiscription = async (
  params: GetPostDiscriptionParams,
  options?: RequestInit
): Promise<getPostDiscriptionResponse> => {
  return coreBackendClient<getPostDiscriptionResponse>(getGetPostDiscriptionUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getGetPostDiscriptionQueryKey = (params?: GetPostDiscriptionParams) => {
  return ['POST', `/post/getPostDiscription`, ...(params ? [params] : [])] as const
}

export const getGetPostDiscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: GetPostDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDiscription>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPostDiscriptionQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostDiscription>>> = ({ signal }) =>
    getPostDiscription(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostDiscription>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostDiscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostDiscription>>
>
export type GetPostDiscriptionQueryError = ApiErrorResponse

export function useGetPostDiscription<
  TData = Awaited<ReturnType<typeof getPostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: GetPostDiscriptionParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDiscription>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getPostDiscription>>,
        TError,
        Awaited<ReturnType<typeof getPostDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostDiscription<
  TData = Awaited<ReturnType<typeof getPostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: GetPostDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostDiscription>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getPostDiscription>>,
        TError,
        Awaited<ReturnType<typeof getPostDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostDiscription<
  TData = Awaited<ReturnType<typeof getPostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: GetPostDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDiscription>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List post descriptions
 */

export function useGetPostDiscription<
  TData = Awaited<ReturnType<typeof getPostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: GetPostDiscriptionParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostDiscription>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostDiscriptionQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postDeleteResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type postDeleteResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type postDeleteResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type postDeleteResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type postDeleteResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type postDeleteResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type postDeleteResponseSuccess = postDeleteResponse200 & {
  headers: Headers
}
export type postDeleteResponseError = (
  | postDeleteResponse400
  | postDeleteResponse401
  | postDeleteResponse403
  | postDeleteResponse422
  | postDeleteResponse500
) & {
  headers: Headers
}

export type postDeleteResponse = postDeleteResponseSuccess | postDeleteResponseError

export const getPostDeleteUrl = (params: PostDeleteParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/post/postDelete?${stringifiedParams}` : `/post/postDelete`
}

/**
 * Deletes a post owned by the authenticated user and archives related content according to the content delete service.
 * @summary Delete my post
 */
export const postDelete = async (
  params: PostDeleteParams,
  options?: RequestInit
): Promise<postDeleteResponse> => {
  return coreBackendClient<postDeleteResponse>(getPostDeleteUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getPostDeleteQueryKey = (params?: PostDeleteParams) => {
  return ['POST', `/post/postDelete`, ...(params ? [params] : [])] as const
}

export const getPostDeleteQueryOptions = <
  TData = Awaited<ReturnType<typeof postDelete>>,
  TError = ApiErrorResponse,
>(
  params: PostDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postDelete>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getPostDeleteQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postDelete>>> = ({ signal }) =>
    postDelete(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postDelete>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof postDelete>>>
export type PostDeleteQueryError = ApiErrorResponse

export function usePostDelete<
  TData = Awaited<ReturnType<typeof postDelete>>,
  TError = ApiErrorResponse,
>(
  params: PostDeleteParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof postDelete>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof postDelete>>,
        TError,
        Awaited<ReturnType<typeof postDelete>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostDelete<
  TData = Awaited<ReturnType<typeof postDelete>>,
  TError = ApiErrorResponse,
>(
  params: PostDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postDelete>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof postDelete>>,
        TError,
        Awaited<ReturnType<typeof postDelete>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostDelete<
  TData = Awaited<ReturnType<typeof postDelete>>,
  TError = ApiErrorResponse,
>(
  params: PostDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postDelete>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete my post
 */

export function usePostDelete<
  TData = Awaited<ReturnType<typeof postDelete>>,
  TError = ApiErrorResponse,
>(
  params: PostDeleteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postDelete>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPostDeleteQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getDashboardCountsResponse200 = {
  data: DashboardCountsResponse
  status: 200
}

export type getDashboardCountsResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getDashboardCountsResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getDashboardCountsResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getDashboardCountsResponseSuccess = getDashboardCountsResponse200 & {
  headers: Headers
}
export type getDashboardCountsResponseError = (
  | getDashboardCountsResponse400
  | getDashboardCountsResponse422
  | getDashboardCountsResponse500
) & {
  headers: Headers
}

export type getDashboardCountsResponse =
  | getDashboardCountsResponseSuccess
  | getDashboardCountsResponseError

export const getGetDashboardCountsUrl = () => {
  return `/post/public/getDashboardCounts`
}

/**
 * Returns public aggregate counts used by the dashboard.
 * @summary Get public dashboard counts
 */
export const getDashboardCounts = async (
  options?: RequestInit
): Promise<getDashboardCountsResponse> => {
  return coreBackendClient<getDashboardCountsResponse>(getGetDashboardCountsUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetDashboardCountsQueryKey = () => {
  return [`/post/public/getDashboardCounts`] as const
}

export const getGetDashboardCountsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardCounts>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardCounts>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDashboardCountsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardCounts>>> = ({ signal }) =>
    getDashboardCounts({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardCounts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardCountsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardCounts>>
>
export type GetDashboardCountsQueryError = ApiErrorResponse

export function useGetDashboardCounts<
  TData = Awaited<ReturnType<typeof getDashboardCounts>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardCounts>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getDashboardCounts>>,
        TError,
        Awaited<ReturnType<typeof getDashboardCounts>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardCounts<
  TData = Awaited<ReturnType<typeof getDashboardCounts>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDashboardCounts>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getDashboardCounts>>,
        TError,
        Awaited<ReturnType<typeof getDashboardCounts>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardCounts<
  TData = Awaited<ReturnType<typeof getDashboardCounts>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardCounts>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get public dashboard counts
 */

export function useGetDashboardCounts<
  TData = Awaited<ReturnType<typeof getDashboardCounts>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardCounts>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDashboardCountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getImageResponse200 = {
  data: Blob
  status: 200
}

export type getImageResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getImageResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getImageResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getImageResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getImageResponseSuccess = getImageResponse200 & {
  headers: Headers
}
export type getImageResponseError = (
  | getImageResponse400
  | getImageResponse404
  | getImageResponse422
  | getImageResponse500
) & {
  headers: Headers
}

export type getImageResponse = getImageResponseSuccess | getImageResponseError

export const getGetImageUrl = (id: string) => {
  return `/post/public/images/${id}`
}

/**
 * Public endpoint that streams a stored inscription image by id.
 * @summary Download post image
 */
export const getImage = async (id: string, options?: RequestInit): Promise<getImageResponse> => {
  return coreBackendClient<getImageResponse>(getGetImageUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetImageQueryKey = (id: string) => {
  return [`/post/public/images/${id}`] as const
}

export const getGetImageQueryOptions = <
  TData = Awaited<ReturnType<typeof getImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetImageQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getImage>>> = ({ signal }) =>
    getImage(id, { signal })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetImageQueryResult = NonNullable<Awaited<ReturnType<typeof getImage>>>
export type GetImageQueryError = ApiErrorResponse

export function useGetImage<
  TData = Awaited<ReturnType<typeof getImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getImage>>,
        TError,
        Awaited<ReturnType<typeof getImage>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImage<
  TData = Awaited<ReturnType<typeof getImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getImage>>,
        TError,
        Awaited<ReturnType<typeof getImage>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImage<
  TData = Awaited<ReturnType<typeof getImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download post image
 */

export function useGetImage<
  TData = Awaited<ReturnType<typeof getImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImage>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetImageQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type updatePostResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type updatePostResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type updatePostResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type updatePostResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type updatePostResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type updatePostResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type updatePostResponseSuccess = updatePostResponse200 & {
  headers: Headers
}
export type updatePostResponseError = (
  | updatePostResponse400
  | updatePostResponse401
  | updatePostResponse403
  | updatePostResponse422
  | updatePostResponse500
) & {
  headers: Headers
}

export type updatePostResponse = updatePostResponseSuccess | updatePostResponseError

export const getUpdatePostUrl = (params: UpdatePostParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/post/updatePost?${stringifiedParams}` : `/post/updatePost`
}

/**
 * Updates post metadata, removes selected images, adds new images, and enforces that at least one image remains and no more than 16 images are attached.
 * @summary Update post metadata and images
 */
export const updatePost = async (
  params: UpdatePostParams,
  updatePostBody?: UpdatePostBody,
  options?: RequestInit
): Promise<updatePostResponse> => {
  return coreBackendClient<updatePostResponse>(getUpdatePostUrl(params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePostBody),
  })
}

export const getUpdatePostMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePost>>,
    TError,
    { params: UpdatePostParams; data?: UpdatePostBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  { params: UpdatePostParams; data?: UpdatePostBody },
  TContext
> => {
  const mutationKey = ['updatePost']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePost>>,
    { params: UpdatePostParams; data?: UpdatePostBody }
  > = (props) => {
    const { params, data } = props ?? {}

    return updatePost(params, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>
export type UpdatePostMutationBody = UpdatePostBody | undefined
export type UpdatePostMutationError = ApiErrorResponse

/**
 * @summary Update post metadata and images
 */
export const useUpdatePost = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePost>>,
      TError,
      { params: UpdatePostParams; data?: UpdatePostBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  { params: UpdatePostParams; data?: UpdatePostBody },
  TContext
> => {
  return useMutation(getUpdatePostMutationOptions(options), queryClient)
}
export type updatePostDiscriptionResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type updatePostDiscriptionResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type updatePostDiscriptionResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type updatePostDiscriptionResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type updatePostDiscriptionResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type updatePostDiscriptionResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type updatePostDiscriptionResponseSuccess = updatePostDiscriptionResponse200 & {
  headers: Headers
}
export type updatePostDiscriptionResponseError = (
  | updatePostDiscriptionResponse400
  | updatePostDiscriptionResponse401
  | updatePostDiscriptionResponse403
  | updatePostDiscriptionResponse422
  | updatePostDiscriptionResponse500
) & {
  headers: Headers
}

export type updatePostDiscriptionResponse =
  | updatePostDiscriptionResponseSuccess
  | updatePostDiscriptionResponseError

export const getUpdatePostDiscriptionUrl = (params: UpdatePostDiscriptionParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/post/updatePostDiscription?${stringifiedParams}`
    : `/post/updatePostDiscription`
}

/**
 * Updates an authenticated user's own description/comment after moderation.
 * @summary Update post description
 */
export const updatePostDiscription = async (
  params: UpdatePostDiscriptionParams,
  options?: RequestInit
): Promise<updatePostDiscriptionResponse> => {
  return coreBackendClient<updatePostDiscriptionResponse>(getUpdatePostDiscriptionUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getUpdatePostDiscriptionQueryKey = (params?: UpdatePostDiscriptionParams) => {
  return ['POST', `/post/updatePostDiscription`, ...(params ? [params] : [])] as const
}

export const getUpdatePostDiscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof updatePostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: UpdatePostDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof updatePostDiscription>>, TError, TData>
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUpdatePostDiscriptionQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof updatePostDiscription>>> = ({ signal }) =>
    updatePostDiscription(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof updatePostDiscription>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdatePostDiscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof updatePostDiscription>>
>
export type UpdatePostDiscriptionQueryError = ApiErrorResponse

export function useUpdatePostDiscription<
  TData = Awaited<ReturnType<typeof updatePostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: UpdatePostDiscriptionParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof updatePostDiscription>>, TError, TData>
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof updatePostDiscription>>,
        TError,
        Awaited<ReturnType<typeof updatePostDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePostDiscription<
  TData = Awaited<ReturnType<typeof updatePostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: UpdatePostDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof updatePostDiscription>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof updatePostDiscription>>,
        TError,
        Awaited<ReturnType<typeof updatePostDiscription>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePostDiscription<
  TData = Awaited<ReturnType<typeof updatePostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: UpdatePostDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof updatePostDiscription>>, TError, TData>
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update post description
 */

export function useUpdatePostDiscription<
  TData = Awaited<ReturnType<typeof updatePostDiscription>>,
  TError = ApiErrorResponse,
>(
  params: UpdatePostDiscriptionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof updatePostDiscription>>, TError, TData>
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdatePostDiscriptionQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type userProfileResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type userProfileResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type userProfileResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type userProfileResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type userProfileResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type userProfileResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type userProfileResponseSuccess = userProfileResponse200 & {
  headers: Headers
}
export type userProfileResponseError = (
  | userProfileResponse400
  | userProfileResponse401
  | userProfileResponse403
  | userProfileResponse422
  | userProfileResponse500
) & {
  headers: Headers
}

export type userProfileResponse = userProfileResponseSuccess | userProfileResponseError

export const getUserProfileUrl = () => {
  return `/post/userProfile`
}

/**
 * Legacy post-module profile endpoint that returns the authenticated user object in the standard envelope.
 * @summary Get current user entity profile
 */
export const userProfile = async (options?: RequestInit): Promise<userProfileResponse> => {
  return coreBackendClient<userProfileResponse>(getUserProfileUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getUserProfileQueryKey = () => {
  return ['POST', `/post/userProfile`] as const
}

export const getUserProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof userProfile>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUserProfileQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userProfile>>> = ({ signal }) =>
    userProfile({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userProfile>>>
export type UserProfileQueryError = ApiErrorResponse

export function useUserProfile<
  TData = Awaited<ReturnType<typeof userProfile>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof userProfile>>,
        TError,
        Awaited<ReturnType<typeof userProfile>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfile<
  TData = Awaited<ReturnType<typeof userProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof userProfile>>,
        TError,
        Awaited<ReturnType<typeof userProfile>>
      >,
      'initialData'
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfile<
  TData = Awaited<ReturnType<typeof userProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user entity profile
 */

export function useUserProfile<
  TData = Awaited<ReturnType<typeof userProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
