/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ApiErrorResponse,
  ApiSuccessResponse,
  CreateReportRequest,
  GetReportsParams,
  ModerateReportRequest,
  ModerationReport,
  ReportQueuedResponse,
} from '../../models'

import { coreBackendClient } from '../../../utils/http/clients/coreBackend.client'

export type moderateReportResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type moderateReportResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type moderateReportResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type moderateReportResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type moderateReportResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type moderateReportResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type moderateReportResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type moderateReportResponseSuccess = moderateReportResponse200 & {
  headers: Headers
}
export type moderateReportResponseError = (
  | moderateReportResponse400
  | moderateReportResponse401
  | moderateReportResponse403
  | moderateReportResponse404
  | moderateReportResponse422
  | moderateReportResponse500
) & {
  headers: Headers
}

export type moderateReportResponse = moderateReportResponseSuccess | moderateReportResponseError

export const getModerateReportUrl = (id: string) => {
  return `/moderate/${id}`
}

/**
 * Runs the moderation chain for a report. Human moderator roles are required when an escalated report needs final resolution.
 * @summary Moderate report
 */
export const moderateReport = async (
  id: string,
  moderateReportRequest?: ModerateReportRequest,
  options?: RequestInit
): Promise<moderateReportResponse> => {
  return coreBackendClient<moderateReportResponse>(getModerateReportUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moderateReportRequest),
  })
}

export const getModerateReportMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof moderateReport>>,
    TError,
    { id: string; data?: ModerateReportRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof moderateReport>>,
  TError,
  { id: string; data?: ModerateReportRequest },
  TContext
> => {
  const mutationKey = ['moderateReport']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof moderateReport>>,
    { id: string; data?: ModerateReportRequest }
  > = (props) => {
    const { id, data } = props ?? {}

    return moderateReport(id, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type ModerateReportMutationResult = NonNullable<Awaited<ReturnType<typeof moderateReport>>>
export type ModerateReportMutationBody = ModerateReportRequest | undefined
export type ModerateReportMutationError = ApiErrorResponse

/**
 * @summary Moderate report
 */
export const useModerateReport = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof moderateReport>>,
      TError,
      { id: string; data?: ModerateReportRequest },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof moderateReport>>,
  TError,
  { id: string; data?: ModerateReportRequest },
  TContext
> => {
  return useMutation(getModerateReportMutationOptions(options), queryClient)
}
export type createReportResponse202 = {
  data: ReportQueuedResponse
  status: 202
}

export type createReportResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type createReportResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type createReportResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type createReportResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type createReportResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type createReportResponseSuccess = createReportResponse202 & {
  headers: Headers
}
export type createReportResponseError = (
  | createReportResponse400
  | createReportResponse401
  | createReportResponse403
  | createReportResponse422
  | createReportResponse500
) & {
  headers: Headers
}

export type createReportResponse = createReportResponseSuccess | createReportResponseError

export const getCreateReportUrl = () => {
  return `/report`
}

/**
 * Accepts a report from the authenticated user, validates target/reporting rules, and queues the report for AI moderation.
 * @summary Submit report
 */
export const createReport = async (
  createReportRequest: CreateReportRequest,
  options?: RequestInit
): Promise<createReportResponse> => {
  return coreBackendClient<createReportResponse>(getCreateReportUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReportRequest),
  })
}

export const getCreateReportMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReport>>,
    TError,
    { data: CreateReportRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReport>>,
  TError,
  { data: CreateReportRequest },
  TContext
> => {
  const mutationKey = ['createReport']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReport>>,
    { data: CreateReportRequest }
  > = (props) => {
    const { data } = props ?? {}

    return createReport(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>
export type CreateReportMutationBody = CreateReportRequest
export type CreateReportMutationError = ApiErrorResponse

/**
 * @summary Submit report
 */
export const useCreateReport = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReport>>,
      TError,
      { data: CreateReportRequest },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createReport>>,
  TError,
  { data: CreateReportRequest },
  TContext
> => {
  return useMutation(getCreateReportMutationOptions(options), queryClient)
}
export type getReportsResponse200 = {
  data: ModerationReport[]
  status: 200
}

export type getReportsResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getReportsResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getReportsResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getReportsResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getReportsResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getReportsResponseSuccess = getReportsResponse200 & {
  headers: Headers
}
export type getReportsResponseError = (
  | getReportsResponse400
  | getReportsResponse401
  | getReportsResponse403
  | getReportsResponse422
  | getReportsResponse500
) & {
  headers: Headers
}

export type getReportsResponse = getReportsResponseSuccess | getReportsResponseError

export const getGetReportsUrl = (params?: GetReportsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/reports?${stringifiedParams}` : `/reports`
}

/**
 * Returns moderation reports ordered by creation time. Moderators may optionally filter by status.
 * @summary List moderation reports
 */
export const getReports = async (
  params?: GetReportsParams,
  options?: RequestInit
): Promise<getReportsResponse> => {
  return coreBackendClient<getReportsResponse>(getGetReportsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetReportsQueryKey = (params?: GetReportsParams) => {
  return [`/reports`, ...(params ? [params] : [])] as const
}

export const getGetReportsQueryOptions = <
  TData = Awaited<ReturnType<typeof getReports>>,
  TError = ApiErrorResponse,
>(
  params?: GetReportsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetReportsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReports>>> = ({ signal }) =>
    getReports(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReports>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getReports>>>
export type GetReportsQueryError = ApiErrorResponse

export function useGetReports<
  TData = Awaited<ReturnType<typeof getReports>>,
  TError = ApiErrorResponse,
>(
  params: undefined | GetReportsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReports>>,
          TError,
          Awaited<ReturnType<typeof getReports>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReports<
  TData = Awaited<ReturnType<typeof getReports>>,
  TError = ApiErrorResponse,
>(
  params?: GetReportsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReports>>,
          TError,
          Awaited<ReturnType<typeof getReports>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReports<
  TData = Awaited<ReturnType<typeof getReports>>,
  TError = ApiErrorResponse,
>(
  params?: GetReportsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List moderation reports
 */

export function useGetReports<
  TData = Awaited<ReturnType<typeof getReports>>,
  TError = ApiErrorResponse,
>(
  params?: GetReportsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReportsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
