/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import type { InscriptionPost } from './inscriptionPost'

export type AddPostWithFileBody = {
  /** Image files. Maximum 16 files, 75 MB each. */
  files: Blob[]
  post?: InscriptionPost
}
