/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Standard error body returned by API exception handlers.
 */
export interface ApiErrorResponse {
  /** Human-readable error message. */
  error_message?: string
  /** HTTP status reason or numeric status used by the handler. */
  http_status?: unknown
  /** HTTP status code. */
  http_status_code?: number
}
