/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Standard success envelope returned by most JSON endpoints.
 */
export interface ApiSuccessResponse {
  /** Endpoint-specific payload. */
  data?: unknown
  /** HTTP status reason used by the response envelope. */
  'http-status'?: unknown
  /** Operation result message. */
  message?: string
}
