/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Type of resource being reported.
 */
export type CreateReportRequestTargetType =
  (typeof CreateReportRequestTargetType)[keyof typeof CreateReportRequestTargetType]

export const CreateReportRequestTargetType = {
  POST: 'POST',
  COMMENT: 'COMMENT',
  USER: 'USER',
} as const
