/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import type { CreateReportRequestReason } from './createReportRequestReason'
import type { CreateReportRequestTargetType } from './createReportRequestTargetType'

/**
 * Request used by authenticated users to report a post, comment, or user.
 */
export interface CreateReportRequest {
  /**
   * Reporter-provided context for moderators. Maximum 1000 characters.
   * @minLength 0
   * @maxLength 1000
   */
  details: string
  /** Reason selected by the reporter. */
  reason: CreateReportRequestReason
  /**
   * MongoDB ObjectId or canonical identifier of the reported resource.
   * @minLength 1
   */
  targetId: string
  /** Type of resource being reported. */
  targetType: CreateReportRequestTargetType
}
