/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Public aggregate counters for the application dashboard.
 */
export interface DashboardCountsResponse {
  /** Posts with extracted geolocation metadata. */
  totalGeoTaggedPosts?: number
  /** Uploaded image objects. */
  totalImages?: number
  /** Published posts. */
  totalPosts?: number
  /** Posts with an English translation available. */
  totalTranslations?: number
  /** Registered users. */
  totalUsers?: number
}
