/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Human-readable inscription description payload.
 */
export interface InscriptionPostDescription {
  /** Detailed inscription description. */
  description?: string
  language?: unknown[]
  scriptLanguage?: unknown[]
  /** Primary subject of the inscription. */
  subject?: string
  /** Display title for the inscription. */
  title?: string
}
