/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import type { InscriptionPostDescription } from './inscriptionPostDescription'

/**
 * Post metadata JSON part.
 */
export interface InscriptionPost {
  /** Localized inscription description and language metadata. */
  description?: InscriptionPostDescription
  script?: unknown[]
  /** High-level post topic. */
  topic?: string
  /** Content type or category. */
  type?: string
  /** Whether the post should be visible publicly. Field name preserves the existing API spelling. */
  visiblity?: boolean
}
