/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import type { ModerateReportRequestAction } from './moderateReportRequestAction'

/**
 * Optional instruction supplied by a moderator when processing a report.
 */
export interface ModerateReportRequest {
  /** Moderation action to apply. If omitted, the moderation chain decides the next transition. */
  action?: ModerateReportRequestAction
  /**
   * Moderator note saved in the report audit trail. Maximum 1000 characters.
   * @minLength 0
   * @maxLength 1000
   */
  note?: string
}
