/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Reporter-selected reason.
 */
export type ModerationReportReason =
  (typeof ModerationReportReason)[keyof typeof ModerationReportReason]

export const ModerationReportReason = {
  SPAM: 'SPAM',
  HATE_SPEECH: 'HATE_SPEECH',
  MISINFORMATION: 'MISINFORMATION',
  HARASSMENT: 'HARASSMENT',
  EXPLICIT_CONTENT: 'EXPLICIT_CONTENT',
  OTHER: 'OTHER',
} as const
