/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import type { ModerationReportActionTaken } from './moderationReportActionTaken'
import type { ModerationReportReason } from './moderationReportReason'
import type { ModerationReportStatus } from './moderationReportStatus'
import type { ModerationReportTargetType } from './moderationReportTargetType'
import type { ObjectId } from './objectId'
import type { ReportAuditEntry } from './reportAuditEntry'

/**
 * Moderation report state, target metadata, AI score, and audit history.
 */
export interface ModerationReport {
  /** Report identifier. */
  _id?: ObjectId
  /** Action applied during moderation. */
  actionTaken?: ModerationReportActionTaken
  activeReportKey?: string
  /** AI confidence score from 0 to 1. */
  aiConfidenceScore?: number
  auditEntries?: ReportAuditEntry[]
  createdAt?: string
  /** Reporter-provided details. */
  details?: string
  /** Reporter-selected reason. */
  reason?: ModerationReportReason
  /** Reporter user id. */
  reporterId?: string
  resolvedAt?: string
  /** Actor that resolved the report. */
  resolvedBy?: string
  /** Current moderation workflow status. */
  status?: ModerationReportStatus
  /** Author id of the reported target. */
  targetAuthorId?: string
  /** Reported target id. */
  targetId?: string
  /** Reported target type. */
  targetType?: ModerationReportTargetType
  updatedAt?: string
  version?: number
}
