/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Moderation action to apply. If omitted, the moderation chain decides the next transition.
 */
export type ModerateReportRequestAction =
  (typeof ModerateReportRequestAction)[keyof typeof ModerateReportRequestAction]

export const ModerateReportRequestAction = {
  NONE: 'NONE',
  WARN: 'WARN',
  REMOVE_CONTENT: 'REMOVE_CONTENT',
  BAN_REPORTER: 'BAN_REPORTER',
  BAN_AUTHOR: 'BAN_AUTHOR',
  ESCALATE: 'ESCALATE',
  DISMISS: 'DISMISS',
} as const
