/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Payload returned after a report is accepted for asynchronous moderation.
 */
export interface ReportQueuedResponse {
  /** Published report event identifier. */
  eventId?: string
  /** Queue processing state. */
  status?: string
  /** Identifier of the reported content or user. */
  targetId?: string
  /** Reported resource type. */
  targetType?: string
}
