/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Single audit trail entry recorded during report moderation.
 */
export interface ReportAuditEntry {
  /** Actor email or system actor name. */
  actor?: string
  /** Audit creation timestamp. */
  createdAt?: string
  /** Audit message. */
  message?: string
}
