/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Editable profile fields for the authenticated user.
 */
export interface UpdateProfileRequest {
  /**
   * Short profile bio. Letters, numbers, and spaces only.
   * @minLength 3
   * @maxLength 150
   * @pattern ^(?=.*[A-Za-z0-9])[A-Za-z0-9 ]+$
   */
  bio?: string
  /**
   * Unique username. Submit only when changing it.
   * @minLength 3
   * @maxLength 25
   */
  username?: string
}
