/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */

/**
 * Profile details returned for the authenticated user.
 */
export interface UserProfile {
  /** Short user bio. */
  bio?: string
  /** Public cover image URL. */
  coverImage?: string
  /** User email address. */
  email?: string
  /** Follower count. */
  followers?: number
  /** User identifier. */
  id?: string
  /** Number of uploaded inscription images. */
  imagesUploaded?: number
  /** OAuth provider display name. */
  name?: string
  /** Reputation points. */
  points?: number
  /** Public profile image URL. */
  profileImage?: string
  /** Total upvotes received on user comments/descriptions. */
  upvotesReceived?: number
  /** Application username. */
  username?: string
}
