/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ApiErrorResponse,
  ApiSuccessResponse,
  UpdateProfileRequest,
  UploadCoverImageBody,
  UploadProfileImageBody,
  UserProfile,
} from '../../models'

import { coreBackendClient } from '../../../utils/http/clients/coreBackend.client'

export type getProfileResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type getProfileResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getProfileResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getProfileResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getProfileResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getProfileResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getProfileResponseSuccess = getProfileResponse200 & {
  headers: Headers
}
export type getProfileResponseError = (
  | getProfileResponse400
  | getProfileResponse401
  | getProfileResponse403
  | getProfileResponse422
  | getProfileResponse500
) & {
  headers: Headers
}

export type getProfileResponse = getProfileResponseSuccess | getProfileResponseError

export const getGetProfileUrl = () => {
  return `/user/profile`
}

/**
 * Returns the profile attached to the JWT subject.
 * @summary Get my profile
 */
export const getProfile = async (options?: RequestInit): Promise<getProfileResponse> => {
  return coreBackendClient<getProfileResponse>(getGetProfileUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetProfileQueryKey = () => {
  return [`/user/profile`] as const
}

export const getGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({ signal }) =>
    getProfile({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getProfile>>>
export type GetProfileQueryError = ApiErrorResponse

export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfile>>,
          TError,
          Awaited<ReturnType<typeof getProfile>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfile>>,
          TError,
          Awaited<ReturnType<typeof getProfile>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my profile
 */

export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getUserImageResponse200 = {
  data: Blob
  status: 200
}

export type getUserImageResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getUserImageResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getUserImageResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getUserImageResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getUserImageResponseSuccess = getUserImageResponse200 & {
  headers: Headers
}
export type getUserImageResponseError = (
  | getUserImageResponse400
  | getUserImageResponse404
  | getUserImageResponse422
  | getUserImageResponse500
) & {
  headers: Headers
}

export type getUserImageResponse = getUserImageResponseSuccess | getUserImageResponseError

export const getGetUserImageUrl = (id: string) => {
  return `/user/public/images/${id}`
}

/**
 * Public endpoint that streams a profile or cover image by id.
 * @summary Download user image
 */
export const getUserImage = async (
  id: string,
  options?: RequestInit
): Promise<getUserImageResponse> => {
  return coreBackendClient<getUserImageResponse>(getGetUserImageUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetUserImageQueryKey = (id: string) => {
  return [`/user/public/images/${id}`] as const
}

export const getGetUserImageQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData>>
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserImageQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserImage>>> = ({ signal }) =>
    getUserImage(id, { signal })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetUserImageQueryResult = NonNullable<Awaited<ReturnType<typeof getUserImage>>>
export type GetUserImageQueryError = ApiErrorResponse

export function useGetUserImage<
  TData = Awaited<ReturnType<typeof getUserImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserImage>>,
          TError,
          Awaited<ReturnType<typeof getUserImage>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserImage<
  TData = Awaited<ReturnType<typeof getUserImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserImage>>,
          TError,
          Awaited<ReturnType<typeof getUserImage>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserImage<
  TData = Awaited<ReturnType<typeof getUserImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download user image
 */

export function useGetUserImage<
  TData = Awaited<ReturnType<typeof getUserImage>>,
  TError = ApiErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserImage>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserImageQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type updateProfileResponse200 = {
  data: UserProfile
  status: 200
}

export type updateProfileResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type updateProfileResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type updateProfileResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type updateProfileResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type updateProfileResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type updateProfileResponseSuccess = updateProfileResponse200 & {
  headers: Headers
}
export type updateProfileResponseError = (
  | updateProfileResponse400
  | updateProfileResponse401
  | updateProfileResponse403
  | updateProfileResponse422
  | updateProfileResponse500
) & {
  headers: Headers
}

export type updateProfileResponse = updateProfileResponseSuccess | updateProfileResponseError

export const getUpdateProfileUrl = () => {
  return `/user/updateProfile`
}

/**
 * Updates the authenticated user's editable profile fields. Bean validation constraints are visible in the request schema.
 * @summary Update my profile
 */
export const updateProfile = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: RequestInit
): Promise<updateProfileResponse> => {
  return coreBackendClient<updateProfileResponse>(getUpdateProfileUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  })
}

export const getUpdateProfileMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: UpdateProfileRequest },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: UpdateProfileRequest },
  TContext
> => {
  const mutationKey = ['updateProfile']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfile>>,
    { data: UpdateProfileRequest }
  > = (props) => {
    const { data } = props ?? {}

    return updateProfile(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfile>>>
export type UpdateProfileMutationBody = UpdateProfileRequest
export type UpdateProfileMutationError = ApiErrorResponse

/**
 * @summary Update my profile
 */
export const useUpdateProfile = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProfile>>,
      TError,
      { data: UpdateProfileRequest },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  { data: UpdateProfileRequest },
  TContext
> => {
  return useMutation(getUpdateProfileMutationOptions(options), queryClient)
}
export type uploadCoverImageResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type uploadCoverImageResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type uploadCoverImageResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type uploadCoverImageResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type uploadCoverImageResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type uploadCoverImageResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type uploadCoverImageResponseSuccess = uploadCoverImageResponse200 & {
  headers: Headers
}
export type uploadCoverImageResponseError = (
  | uploadCoverImageResponse400
  | uploadCoverImageResponse401
  | uploadCoverImageResponse403
  | uploadCoverImageResponse422
  | uploadCoverImageResponse500
) & {
  headers: Headers
}

export type uploadCoverImageResponse =
  | uploadCoverImageResponseSuccess
  | uploadCoverImageResponseError

export const getUploadCoverImageUrl = () => {
  return `/user/uploadCoverImage`
}

/**
 * Replaces the authenticated user's cover image. Accepts one multipart image file using the configured extension allow-list.
 * @summary Upload cover image
 */
export const uploadCoverImage = async (
  uploadCoverImageBody?: UploadCoverImageBody,
  options?: RequestInit
): Promise<uploadCoverImageResponse> => {
  return coreBackendClient<uploadCoverImageResponse>(getUploadCoverImageUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(uploadCoverImageBody),
  })
}

export const getUploadCoverImageMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadCoverImage>>,
    TError,
    { data?: UploadCoverImageBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadCoverImage>>,
  TError,
  { data?: UploadCoverImageBody },
  TContext
> => {
  const mutationKey = ['uploadCoverImage']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadCoverImage>>,
    { data?: UploadCoverImageBody }
  > = (props) => {
    const { data } = props ?? {}

    return uploadCoverImage(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadCoverImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadCoverImage>>
>
export type UploadCoverImageMutationBody = UploadCoverImageBody | undefined
export type UploadCoverImageMutationError = ApiErrorResponse

/**
 * @summary Upload cover image
 */
export const useUploadCoverImage = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadCoverImage>>,
      TError,
      { data?: UploadCoverImageBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof uploadCoverImage>>,
  TError,
  { data?: UploadCoverImageBody },
  TContext
> => {
  return useMutation(getUploadCoverImageMutationOptions(options), queryClient)
}
export type uploadProfileImageResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type uploadProfileImageResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type uploadProfileImageResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type uploadProfileImageResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type uploadProfileImageResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type uploadProfileImageResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type uploadProfileImageResponseSuccess = uploadProfileImageResponse200 & {
  headers: Headers
}
export type uploadProfileImageResponseError = (
  | uploadProfileImageResponse400
  | uploadProfileImageResponse401
  | uploadProfileImageResponse403
  | uploadProfileImageResponse422
  | uploadProfileImageResponse500
) & {
  headers: Headers
}

export type uploadProfileImageResponse =
  | uploadProfileImageResponseSuccess
  | uploadProfileImageResponseError

export const getUploadProfileImageUrl = () => {
  return `/user/uploadProfileImage`
}

/**
 * Replaces the authenticated user's profile image. Accepts one multipart image file using the configured extension allow-list.
 * @summary Upload profile image
 */
export const uploadProfileImage = async (
  uploadProfileImageBody?: UploadProfileImageBody,
  options?: RequestInit
): Promise<uploadProfileImageResponse> => {
  return coreBackendClient<uploadProfileImageResponse>(getUploadProfileImageUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(uploadProfileImageBody),
  })
}

export const getUploadProfileImageMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadProfileImage>>,
    TError,
    { data?: UploadProfileImageBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadProfileImage>>,
  TError,
  { data?: UploadProfileImageBody },
  TContext
> => {
  const mutationKey = ['uploadProfileImage']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadProfileImage>>,
    { data?: UploadProfileImageBody }
  > = (props) => {
    const { data } = props ?? {}

    return uploadProfileImage(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadProfileImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadProfileImage>>
>
export type UploadProfileImageMutationBody = UploadProfileImageBody | undefined
export type UploadProfileImageMutationError = ApiErrorResponse

/**
 * @summary Upload profile image
 */
export const useUploadProfileImage = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadProfileImage>>,
      TError,
      { data?: UploadProfileImageBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof uploadProfileImage>>,
  TError,
  { data?: UploadProfileImageBody },
  TContext
> => {
  return useMutation(getUploadProfileImageMutationOptions(options), queryClient)
}
