/**
 * Generated by orval v8.11.0 
 * Do not edit manually.
 * Stone Inscription API
 * REST API for OAuth authentication, user profiles, inscription posts, images, public dashboard metrics, and moderation reports.

Most JSON endpoints return a standard envelope with `message`, `http-status`, and `data`. Protected endpoints use a JWT bearer token in the `Authorization` header.

 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AccessTokenResponse,
  ApiErrorResponse,
  ApiSuccessResponse,
  ApproveAdminRequestParams,
  GetMethodNameParams,
  UpdateLastActive204,
} from '../../models'

import { coreBackendClient } from '../../../utils/http/clients/coreBackend.client'

export type getMethodNameResponse200 = {
  data: string
  status: 200
}

export type getMethodNameResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getMethodNameResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getMethodNameResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getMethodNameResponseSuccess = getMethodNameResponse200 & {
  headers: Headers
}
export type getMethodNameResponseError = (
  | getMethodNameResponse400
  | getMethodNameResponse422
  | getMethodNameResponse500
) & {
  headers: Headers
}

export type getMethodNameResponse = getMethodNameResponseSuccess | getMethodNameResponseError

export const getGetMethodNameUrl = (params: GetMethodNameParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/api/v1/?${stringifiedParams}` : `/api/v1/`
}

/**
 * Returns a minimal success message for connectivity checks.
 * @summary API smoke test
 */
export const getMethodName = async (
  params: GetMethodNameParams,
  options?: RequestInit
): Promise<getMethodNameResponse> => {
  return coreBackendClient<getMethodNameResponse>(getGetMethodNameUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getGetMethodNameMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getMethodName>>,
    TError,
    { params: GetMethodNameParams },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof getMethodName>>,
  TError,
  { params: GetMethodNameParams },
  TContext
> => {
  const mutationKey = ['getMethodName']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getMethodName>>,
    { params: GetMethodNameParams }
  > = (props) => {
    const { params } = props ?? {}

    return getMethodName(params)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetMethodNameMutationResult = NonNullable<Awaited<ReturnType<typeof getMethodName>>>

export type GetMethodNameMutationError = ApiErrorResponse

/**
 * @summary API smoke test
 */
export const useGetMethodName = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getMethodName>>,
      TError,
      { params: GetMethodNameParams },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getMethodName>>,
  TError,
  { params: GetMethodNameParams },
  TContext
> => {
  return useMutation(getGetMethodNameMutationOptions(options), queryClient)
}
export type authResponse200 = {
  data: string
  status: 200
}

export type authResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type authResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type authResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type authResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type authResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type authResponseSuccess = authResponse200 & {
  headers: Headers
}
export type authResponseError = (
  | authResponse400
  | authResponse401
  | authResponse403
  | authResponse422
  | authResponse500
) & {
  headers: Headers
}

export type authResponse = authResponseSuccess | authResponseError

export const getAuthUrl = () => {
  return `/api/v1/auth`
}

/**
 * Requires an admin role and returns a simple authenticated message.
 * @summary Admin auth check
 */
export const auth = async (options?: RequestInit): Promise<authResponse> => {
  return coreBackendClient<authResponse>(getAuthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getAuthMutationOptions = <TError = ApiErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof auth>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof auth>>, TError, void, TContext> => {
  const mutationKey = ['auth']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof auth>>, void> = () => {
    return auth()
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthMutationResult = NonNullable<Awaited<ReturnType<typeof auth>>>

export type AuthMutationError = ApiErrorResponse

/**
 * @summary Admin auth check
 */
export const useAuth = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof auth>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof auth>>, TError, void, TContext> => {
  return useMutation(getAuthMutationOptions(options), queryClient)
}
export type facebookLoginResponse200 = {
  data: string
  status: 200
}

export type facebookLoginResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type facebookLoginResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type facebookLoginResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type facebookLoginResponseSuccess = facebookLoginResponse200 & {
  headers: Headers
}
export type facebookLoginResponseError = (
  | facebookLoginResponse400
  | facebookLoginResponse422
  | facebookLoginResponse500
) & {
  headers: Headers
}

export type facebookLoginResponse = facebookLoginResponseSuccess | facebookLoginResponseError

export const getFacebookLoginUrl = () => {
  return `/api/v1/auth/facebook`
}

/**
 * Legacy endpoint that returns the Facebook OAuth redirect target as text.
 * @summary Facebook login redirect marker
 */
export const facebookLogin = async (options?: RequestInit): Promise<facebookLoginResponse> => {
  return coreBackendClient<facebookLoginResponse>(getFacebookLoginUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getFacebookLoginMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof facebookLogin>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof facebookLogin>>, TError, void, TContext> => {
  const mutationKey = ['facebookLogin']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof facebookLogin>>, void> = () => {
    return facebookLogin()
  }

  return { mutationFn, ...mutationOptions }
}

export type FacebookLoginMutationResult = NonNullable<Awaited<ReturnType<typeof facebookLogin>>>

export type FacebookLoginMutationError = ApiErrorResponse

/**
 * @summary Facebook login redirect marker
 */
export const useFacebookLogin = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof facebookLogin>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof facebookLogin>>, TError, void, TContext> => {
  return useMutation(getFacebookLoginMutationOptions(options), queryClient)
}
export type authTokenResponse200 = {
  data: string
  status: 200
}

export type authTokenResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type authTokenResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type authTokenResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type authTokenResponseSuccess = authTokenResponse200 & {
  headers: Headers
}
export type authTokenResponseError = (
  | authTokenResponse400
  | authTokenResponse422
  | authTokenResponse500
) & {
  headers: Headers
}

export type authTokenResponse = authTokenResponseSuccess | authTokenResponseError

export const getAuthTokenUrl = () => {
  return `/api/v1/auth/token`
}

/**
 * Returns a text message used after successful authentication flows.
 * @summary Token success marker
 */
export const authToken = async (options?: RequestInit): Promise<authTokenResponse> => {
  return coreBackendClient<authTokenResponse>(getAuthTokenUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getAuthTokenMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authToken>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof authToken>>, TError, void, TContext> => {
  const mutationKey = ['authToken']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authToken>>, void> = () => {
    return authToken()
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authToken>>>

export type AuthTokenMutationError = ApiErrorResponse

/**
 * @summary Token success marker
 */
export const useAuthToken = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authToken>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authToken>>, TError, void, TContext> => {
  return useMutation(getAuthTokenMutationOptions(options), queryClient)
}
export type authRoleResponse200 = {
  data: string
  status: 200
}

export type authRoleResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type authRoleResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type authRoleResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type authRoleResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type authRoleResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type authRoleResponseSuccess = authRoleResponse200 & {
  headers: Headers
}
export type authRoleResponseError = (
  | authRoleResponse400
  | authRoleResponse401
  | authRoleResponse403
  | authRoleResponse422
  | authRoleResponse500
) & {
  headers: Headers
}

export type authRoleResponse = authRoleResponseSuccess | authRoleResponseError

export const getAuthRoleUrl = () => {
  return `/api/v1/authrole`
}

/**
 * Requires either user or admin role.
 * @summary User or admin role check
 */
export const authRole = async (options?: RequestInit): Promise<authRoleResponse> => {
  return coreBackendClient<authRoleResponse>(getAuthRoleUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getAuthRoleMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authRole>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof authRole>>, TError, void, TContext> => {
  const mutationKey = ['authRole']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRole>>, void> = () => {
    return authRole()
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthRoleMutationResult = NonNullable<Awaited<ReturnType<typeof authRole>>>

export type AuthRoleMutationError = ApiErrorResponse

/**
 * @summary User or admin role check
 */
export const useAuthRole = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authRole>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authRole>>, TError, void, TContext> => {
  return useMutation(getAuthRoleMutationOptions(options), queryClient)
}
export type getfailResponse200 = {
  data: string
  status: 200
}

export type getfailResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getfailResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getfailResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type getfailResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type getfailResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getfailResponseSuccess = getfailResponse200 & {
  headers: Headers
}
export type getfailResponseError = (
  | getfailResponse400
  | getfailResponse401
  | getfailResponse403
  | getfailResponse422
  | getfailResponse500
) & {
  headers: Headers
}

export type getfailResponse = getfailResponseSuccess | getfailResponseError

export const getGetfailUrl = () => {
  return `/api/v1/fail`
}

/**
 * Requires a user role and returns a simple role-check message.
 * @summary User role check
 */
export const getfail = async (options?: RequestInit): Promise<getfailResponse> => {
  return coreBackendClient<getfailResponse>(getGetfailUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetfailMutationOptions = <TError = ApiErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof getfail>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof getfail>>, TError, void, TContext> => {
  const mutationKey = ['getfail']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof getfail>>, void> = () => {
    return getfail()
  }

  return { mutationFn, ...mutationOptions }
}

export type GetfailMutationResult = NonNullable<Awaited<ReturnType<typeof getfail>>>

export type GetfailMutationError = ApiErrorResponse

/**
 * @summary User role check
 */
export const useGetfail = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof getfail>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof getfail>>, TError, void, TContext> => {
  return useMutation(getGetfailMutationOptions(options), queryClient)
}
export type noAuthResponse200 = {
  data: string
  status: 200
}

export type noAuthResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type noAuthResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type noAuthResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type noAuthResponseSuccess = noAuthResponse200 & {
  headers: Headers
}
export type noAuthResponseError = (noAuthResponse400 | noAuthResponse422 | noAuthResponse500) & {
  headers: Headers
}

export type noAuthResponse = noAuthResponseSuccess | noAuthResponseError

export const getNoAuthUrl = () => {
  return `/api/v1/noauth/check`
}

/**
 * Confirms that public no-auth routes are reachable.
 * @summary Public auth health check
 */
export const noAuth = async (options?: RequestInit): Promise<noAuthResponse> => {
  return coreBackendClient<noAuthResponse>(getNoAuthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getNoAuthMutationOptions = <TError = ApiErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof noAuth>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof noAuth>>, TError, void, TContext> => {
  const mutationKey = ['noAuth']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof noAuth>>, void> = () => {
    return noAuth()
  }

  return { mutationFn, ...mutationOptions }
}

export type NoAuthMutationResult = NonNullable<Awaited<ReturnType<typeof noAuth>>>

export type NoAuthMutationError = ApiErrorResponse

/**
 * @summary Public auth health check
 */
export const useNoAuth = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof noAuth>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof noAuth>>, TError, void, TContext> => {
  return useMutation(getNoAuthMutationOptions(options), queryClient)
}
export type approveAdminRequestResponse302 = {
  data: void
  status: 302
}

export type approveAdminRequestResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type approveAdminRequestResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type approveAdminRequestResponse500 = {
  data: ApiErrorResponse
  status: 500
}
export type approveAdminRequestResponseError = (
  | approveAdminRequestResponse302
  | approveAdminRequestResponse400
  | approveAdminRequestResponse422
  | approveAdminRequestResponse500
) & {
  headers: Headers
}

export type approveAdminRequestResponse = approveAdminRequestResponseError

export const getApproveAdminRequestUrl = (params: ApproveAdminRequestParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/oauth2/admin/approve?${stringifiedParams}`
    : `/oauth2/admin/approve`
}

/**
 * Consumes an emailed approval token and redirects the browser to the configured approval-result page.
 * @summary Approve admin request
 */
export const approveAdminRequest = async (
  params: ApproveAdminRequestParams,
  options?: RequestInit
): Promise<approveAdminRequestResponse> => {
  return coreBackendClient<approveAdminRequestResponse>(getApproveAdminRequestUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getApproveAdminRequestMutationOptions = <
  TError = void | ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approveAdminRequest>>,
    TError,
    { params: ApproveAdminRequestParams },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof approveAdminRequest>>,
  TError,
  { params: ApproveAdminRequestParams },
  TContext
> => {
  const mutationKey = ['approveAdminRequest']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approveAdminRequest>>,
    { params: ApproveAdminRequestParams }
  > = (props) => {
    const { params } = props ?? {}

    return approveAdminRequest(params)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApproveAdminRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof approveAdminRequest>>
>

export type ApproveAdminRequestMutationError = void | ApiErrorResponse

/**
 * @summary Approve admin request
 */
export const useApproveAdminRequest = <TError = void | ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approveAdminRequest>>,
      TError,
      { params: ApproveAdminRequestParams },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approveAdminRequest>>,
  TError,
  { params: ApproveAdminRequestParams },
  TContext
> => {
  return useMutation(getApproveAdminRequestMutationOptions(options), queryClient)
}
export type adminLoginDefaultResponse200 = {
  data: void
  status: 200
}

export type adminLoginDefaultResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type adminLoginDefaultResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type adminLoginDefaultResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type adminLoginDefaultResponseSuccess = adminLoginDefaultResponse200 & {
  headers: Headers
}
export type adminLoginDefaultResponseError = (
  | adminLoginDefaultResponse400
  | adminLoginDefaultResponse422
  | adminLoginDefaultResponse500
) & {
  headers: Headers
}

export type adminLoginDefaultResponse =
  | adminLoginDefaultResponseSuccess
  | adminLoginDefaultResponseError

export const getAdminLoginDefaultUrl = () => {
  return `/oauth2/admin/login`
}

/**
 * Starts admin login using the configured default OAuth provider.
 * @summary Start default admin OAuth login
 */
export const adminLoginDefault = async (
  options?: RequestInit
): Promise<adminLoginDefaultResponse> => {
  return coreBackendClient<adminLoginDefaultResponse>(getAdminLoginDefaultUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getAdminLoginDefaultMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLoginDefault>>,
    TError,
    void,
    TContext
  >
}): UseMutationOptions<Awaited<ReturnType<typeof adminLoginDefault>>, TError, void, TContext> => {
  const mutationKey = ['adminLoginDefault']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminLoginDefault>>, void> = () => {
    return adminLoginDefault()
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminLoginDefaultMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminLoginDefault>>
>

export type AdminLoginDefaultMutationError = ApiErrorResponse

/**
 * @summary Start default admin OAuth login
 */
export const useAdminLoginDefault = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminLoginDefault>>,
      TError,
      void,
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof adminLoginDefault>>, TError, void, TContext> => {
  return useMutation(getAdminLoginDefaultMutationOptions(options), queryClient)
}
export type adminLoginResponse200 = {
  data: void
  status: 200
}

export type adminLoginResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type adminLoginResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type adminLoginResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type adminLoginResponseSuccess = adminLoginResponse200 & {
  headers: Headers
}
export type adminLoginResponseError = (
  | adminLoginResponse400
  | adminLoginResponse422
  | adminLoginResponse500
) & {
  headers: Headers
}

export type adminLoginResponse = adminLoginResponseSuccess | adminLoginResponseError

export const getAdminLoginUrl = (provider: string) => {
  return `/oauth2/admin/login/${provider}`
}

/**
 * Starts OAuth login for an approved admin account.
 * @summary Start admin OAuth login
 */
export const adminLogin = async (
  provider: string,
  options?: RequestInit
): Promise<adminLoginResponse> => {
  return coreBackendClient<adminLoginResponse>(getAdminLoginUrl(provider), {
    ...options,
    method: 'GET',
  })
}

export const getAdminLoginMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { provider: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { provider: string },
  TContext
> => {
  const mutationKey = ['adminLogin']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminLogin>>,
    { provider: string }
  > = (props) => {
    const { provider } = props ?? {}

    return adminLogin(provider)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof adminLogin>>>

export type AdminLoginMutationError = ApiErrorResponse

/**
 * @summary Start admin OAuth login
 */
export const useAdminLogin = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminLogin>>,
      TError,
      { provider: string },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { provider: string },
  TContext
> => {
  return useMutation(getAdminLoginMutationOptions(options), queryClient)
}
export type adminRegisterDefaultResponse200 = {
  data: void
  status: 200
}

export type adminRegisterDefaultResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type adminRegisterDefaultResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type adminRegisterDefaultResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type adminRegisterDefaultResponseSuccess = adminRegisterDefaultResponse200 & {
  headers: Headers
}
export type adminRegisterDefaultResponseError = (
  | adminRegisterDefaultResponse400
  | adminRegisterDefaultResponse422
  | adminRegisterDefaultResponse500
) & {
  headers: Headers
}

export type adminRegisterDefaultResponse =
  | adminRegisterDefaultResponseSuccess
  | adminRegisterDefaultResponseError

export const getAdminRegisterDefaultUrl = () => {
  return `/oauth2/admin/register`
}

/**
 * Starts admin registration using the configured default OAuth provider.
 * @summary Start default admin registration
 */
export const adminRegisterDefault = async (
  options?: RequestInit
): Promise<adminRegisterDefaultResponse> => {
  return coreBackendClient<adminRegisterDefaultResponse>(getAdminRegisterDefaultUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getAdminRegisterDefaultMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminRegisterDefault>>,
    TError,
    void,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminRegisterDefault>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['adminRegisterDefault']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminRegisterDefault>>,
    void
  > = () => {
    return adminRegisterDefault()
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminRegisterDefaultMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminRegisterDefault>>
>

export type AdminRegisterDefaultMutationError = ApiErrorResponse

/**
 * @summary Start default admin registration
 */
export const useAdminRegisterDefault = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminRegisterDefault>>,
      TError,
      void,
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof adminRegisterDefault>>, TError, void, TContext> => {
  return useMutation(getAdminRegisterDefaultMutationOptions(options), queryClient)
}
export type adminRegisterResponse200 = {
  data: void
  status: 200
}

export type adminRegisterResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type adminRegisterResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type adminRegisterResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type adminRegisterResponseSuccess = adminRegisterResponse200 & {
  headers: Headers
}
export type adminRegisterResponseError = (
  | adminRegisterResponse400
  | adminRegisterResponse422
  | adminRegisterResponse500
) & {
  headers: Headers
}

export type adminRegisterResponse = adminRegisterResponseSuccess | adminRegisterResponseError

export const getAdminRegisterUrl = (provider: string) => {
  return `/oauth2/admin/register/${provider}`
}

/**
 * Starts OAuth flow for an admin registration request.
 * @summary Start admin registration
 */
export const adminRegister = async (
  provider: string,
  options?: RequestInit
): Promise<adminRegisterResponse> => {
  return coreBackendClient<adminRegisterResponse>(getAdminRegisterUrl(provider), {
    ...options,
    method: 'GET',
  })
}

export const getAdminRegisterMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminRegister>>,
    TError,
    { provider: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminRegister>>,
  TError,
  { provider: string },
  TContext
> => {
  const mutationKey = ['adminRegister']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminRegister>>,
    { provider: string }
  > = (props) => {
    const { provider } = props ?? {}

    return adminRegister(provider)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdminRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof adminRegister>>>

export type AdminRegisterMutationError = ApiErrorResponse

/**
 * @summary Start admin registration
 */
export const useAdminRegister = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminRegister>>,
      TError,
      { provider: string },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adminRegister>>,
  TError,
  { provider: string },
  TContext
> => {
  return useMutation(getAdminRegisterMutationOptions(options), queryClient)
}
export type updateLastActiveResponse204 = {
  data: UpdateLastActive204
  status: 204
}

export type updateLastActiveResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type updateLastActiveResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type updateLastActiveResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type updateLastActiveResponseSuccess = updateLastActiveResponse204 & {
  headers: Headers
}
export type updateLastActiveResponseError = (
  | updateLastActiveResponse400
  | updateLastActiveResponse422
  | updateLastActiveResponse500
) & {
  headers: Headers
}

export type updateLastActiveResponse =
  | updateLastActiveResponseSuccess
  | updateLastActiveResponseError

export const getUpdateLastActiveUrl = () => {
  return `/oauth2/authenticated/active`
}

/**
 * Refreshes last-use time for the refresh-token session. Returns no content on success.
 * @summary Mark session active
 */
export const updateLastActive = async (
  options?: RequestInit
): Promise<updateLastActiveResponse> => {
  return coreBackendClient<updateLastActiveResponse>(getUpdateLastActiveUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getUpdateLastActiveQueryKey = () => {
  return ['POST', `/oauth2/authenticated/active`] as const
}

export const getUpdateLastActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof updateLastActive>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLastActive>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUpdateLastActiveQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof updateLastActive>>> = ({ signal }) =>
    updateLastActive({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof updateLastActive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateLastActiveQueryResult = NonNullable<Awaited<ReturnType<typeof updateLastActive>>>
export type UpdateLastActiveQueryError = ApiErrorResponse

export function useUpdateLastActive<
  TData = Awaited<ReturnType<typeof updateLastActive>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLastActive>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateLastActive>>,
          TError,
          Awaited<ReturnType<typeof updateLastActive>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateLastActive<
  TData = Awaited<ReturnType<typeof updateLastActive>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLastActive>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateLastActive>>,
          TError,
          Awaited<ReturnType<typeof updateLastActive>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateLastActive<
  TData = Awaited<ReturnType<typeof updateLastActive>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLastActive>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mark session active
 */

export function useUpdateLastActive<
  TData = Awaited<ReturnType<typeof updateLastActive>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateLastActive>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdateLastActiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type refreshTokenResponse200 = {
  data: AccessTokenResponse
  status: 200
}

export type refreshTokenResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type refreshTokenResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type refreshTokenResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type refreshTokenResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type refreshTokenResponseSuccess = refreshTokenResponse200 & {
  headers: Headers
}
export type refreshTokenResponseError = (
  | refreshTokenResponse400
  | refreshTokenResponse401
  | refreshTokenResponse422
  | refreshTokenResponse500
) & {
  headers: Headers
}

export type refreshTokenResponse = refreshTokenResponseSuccess | refreshTokenResponseError

export const getRefreshTokenUrl = () => {
  return `/oauth2/authenticated/refresh-token`
}

/**
 * Rotates the HTTP-only refresh token cookie and returns a new JWT access token.
 * @summary Refresh access token
 */
export const refreshToken = async (options?: RequestInit): Promise<refreshTokenResponse> => {
  return coreBackendClient<refreshTokenResponse>(getRefreshTokenUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getRefreshTokenQueryKey = () => {
  return ['POST', `/oauth2/authenticated/refresh-token`] as const
}

export const getRefreshTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof refreshToken>>,
  TError = ApiErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refreshToken>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getRefreshTokenQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof refreshToken>>> = ({ signal }) =>
    refreshToken({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RefreshTokenQueryResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
export type RefreshTokenQueryError = ApiErrorResponse

export function useRefreshToken<
  TData = Awaited<ReturnType<typeof refreshToken>>,
  TError = ApiErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof refreshToken>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof refreshToken>>,
          TError,
          Awaited<ReturnType<typeof refreshToken>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefreshToken<
  TData = Awaited<ReturnType<typeof refreshToken>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refreshToken>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof refreshToken>>,
          TError,
          Awaited<ReturnType<typeof refreshToken>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRefreshToken<
  TData = Awaited<ReturnType<typeof refreshToken>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refreshToken>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Refresh access token
 */

export function useRefreshToken<
  TData = Awaited<ReturnType<typeof refreshToken>>,
  TError = ApiErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refreshToken>>, TError, TData>>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRefreshTokenQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type loginResponse200 = {
  data: void
  status: 200
}

export type loginResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type loginResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type loginResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers
}
export type loginResponseError = (loginResponse400 | loginResponse422 | loginResponse500) & {
  headers: Headers
}

export type loginResponse = loginResponseSuccess | loginResponseError

export const getLoginUrl = () => {
  return `/oauth2/login`
}

/**
 * Redirects to the configured default OAuth provider.
 * @summary Start default user OAuth login
 */
export const login = async (options?: RequestInit): Promise<loginResponse> => {
  return coreBackendClient<loginResponse>(getLoginUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getLoginMutationOptions = <TError = ApiErrorResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, void, TContext> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, void> = () => {
    return login()
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>

export type LoginMutationError = ApiErrorResponse

/**
 * @summary Start default user OAuth login
 */
export const useLogin = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof login>>, TError, void, TContext> => {
  return useMutation(getLoginMutationOptions(options), queryClient)
}
export type loginWithProviderResponse302 = {
  data: void
  status: 302
}

export type loginWithProviderResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type loginWithProviderResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type loginWithProviderResponse500 = {
  data: ApiErrorResponse
  status: 500
}
export type loginWithProviderResponseError = (
  | loginWithProviderResponse302
  | loginWithProviderResponse400
  | loginWithProviderResponse422
  | loginWithProviderResponse500
) & {
  headers: Headers
}

export type loginWithProviderResponse = loginWithProviderResponseError

export const getLoginWithProviderUrl = (provider: string) => {
  return `/oauth2/login/${provider}`
}

/**
 * Stores the user-login flow marker and redirects to the configured OAuth provider.
 * @summary Start user OAuth login
 */
export const loginWithProvider = async (
  provider: string,
  options?: RequestInit
): Promise<loginWithProviderResponse> => {
  return coreBackendClient<loginWithProviderResponse>(getLoginWithProviderUrl(provider), {
    ...options,
    method: 'GET',
  })
}

export const getLoginWithProviderMutationOptions = <
  TError = void | ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginWithProvider>>,
    TError,
    { provider: string },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginWithProvider>>,
  TError,
  { provider: string },
  TContext
> => {
  const mutationKey = ['loginWithProvider']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginWithProvider>>,
    { provider: string }
  > = (props) => {
    const { provider } = props ?? {}

    return loginWithProvider(provider)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginWithProviderMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginWithProvider>>
>

export type LoginWithProviderMutationError = void | ApiErrorResponse

/**
 * @summary Start user OAuth login
 */
export const useLoginWithProvider = <TError = void | ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginWithProvider>>,
      TError,
      { provider: string },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof loginWithProvider>>,
  TError,
  { provider: string },
  TContext
> => {
  return useMutation(getLoginWithProviderMutationOptions(options), queryClient)
}
export type logoutAuthResponse200 = {
  data: ApiSuccessResponse
  status: 200
}

export type logoutAuthResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type logoutAuthResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type logoutAuthResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type logoutAuthResponseSuccess = logoutAuthResponse200 & {
  headers: Headers
}
export type logoutAuthResponseError = (
  | logoutAuthResponse400
  | logoutAuthResponse422
  | logoutAuthResponse500
) & {
  headers: Headers
}

export type logoutAuthResponse = logoutAuthResponseSuccess | logoutAuthResponseError

export const getLogoutAuthUrl = () => {
  return `/oauth2/logout`
}

/**
 * Revokes the refresh token cookie when present and expires the browser cookie.
 * @summary Logout
 */
export const logoutAuth = async (options?: RequestInit): Promise<logoutAuthResponse> => {
  return coreBackendClient<logoutAuthResponse>(getLogoutAuthUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getLogoutAuthMutationOptions = <
  TError = ApiErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof logoutAuth>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof logoutAuth>>, TError, void, TContext> => {
  const mutationKey = ['logoutAuth']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutAuth>>, void> = () => {
    return logoutAuth()
  }

  return { mutationFn, ...mutationOptions }
}

export type LogoutAuthMutationResult = NonNullable<Awaited<ReturnType<typeof logoutAuth>>>

export type LogoutAuthMutationError = ApiErrorResponse

/**
 * @summary Logout
 */
export const useLogoutAuth = <TError = ApiErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof logoutAuth>>, TError, void, TContext>
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof logoutAuth>>, TError, void, TContext> => {
  return useMutation(getLogoutAuthMutationOptions(options), queryClient)
}
